import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  ar: {
    'nav.menu': 'المنيو',
    'nav.cart': 'السلة',
    'nav.admin': 'لوحة التحكم',
    'hero.title': "Bite's Menu",
    'hero.subtitle': 'اطلب ألذ الوجبات بضغطة زر',
    'search.placeholder': 'ابحث عن وجبتك المفضلة...',
    'categories.all': 'الكل',
    'offers.title': 'عروض حصرية',
    'offers.limited': 'عرض لفترة محدودة',
    'product.available': 'متاح للطلب',
    'product.unavailable': 'غير متوفر',
    'product.add_to_cart': 'أضف للسلة',
    'product.details': 'عرض التفاصيل',
    'cart.title': 'سلة المشتريات',
    'cart.empty': 'سلة المشتريات فارغة',
    'cart.empty_subtitle': 'ابدأ بإضافة بعض الوجبات اللذيذة للمنيو',
    'cart.browse': 'تصفح المنيو',
    'cart.clear': 'مسح السلة',
    'cart.order_details': 'تفاصيل الطلب',
    'cart.delivery': 'توصيل',
    'cart.pickup': 'استلام',
    'cart.name_placeholder': 'الاسم بالكامل',
    'cart.phone_placeholder': 'رقم الموبايل',
    'cart.address_placeholder': 'العنوان بالتفصيل',
    'cart.notes_placeholder': 'ملاحظات إضافية',
    'cart.payment_method': 'طريقة الدفع',
    'cart.cash': 'كاش عند الاستلام',
    'cart.instapay': 'انستا باي (InstaPay)',
    'cart.card': 'فيزا / ماستر كارد',
    'cart.wallet': 'محفظة إلكترونية (كاش)',
    'cart.subtotal': 'المجموع',
    'cart.delivery_fee': 'خدمة التوصيل',
    'cart.total': 'الإجمالي',
    'cart.send_whatsapp': 'إرسال الطلب للواتساب',
    'cart.download_pdf': 'تحميل الفاتورة (PDF)',
    'cart.success_title': 'تم إرسال طلبك بنجاح!',
    'cart.success_subtitle': "شكراً لاختيارك Bite's. سيتم التواصل معك قريباً عبر الواتساب لتأكيد الطلب.",
    'cart.back_to_menu': 'العودة للمنيو',
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ ما',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.add': 'إضافة',
    'admin.title': 'لوحة التحكم',
    'admin.products': 'إدارة المنتجات',
    'admin.categories': 'إدارة الأقسام',
    'admin.orders': 'إدارة الطلبات',
    'admin.offers': 'إدارة العروض',
    'admin.settings': 'إعدادات النظام',
    'admin.errors': 'سجل الأخطاء',
    'admin.logout': 'تسجيل الخروج',
    'login.title': 'دخول الإدارة',
    'login.subtitle': 'أدخل كلمة المرور للوصول للوحة التحكم',
    'login.password_placeholder': 'كلمة المرور',
    'login.button': 'دخول',
    'login.error': 'كلمة المرور غير صحيحة',
    'login.welcome': 'أهلاً بك',
    'login.admin_role': 'مدير النظام',
    'admin.add_product': 'إضافة منتج',
    'admin.edit_product': 'تعديل منتج',
    'admin.product_name': 'اسم المنتج',
    'admin.product_price': 'السعر',
    'admin.product_category': 'القسم',
    'admin.product_description': 'الوصف',
    'admin.product_image': 'صورة المنتج',
    'admin.product_upload': 'رفع صورة من الجهاز',
    'admin.product_url': 'أو ضع رابط الصورة هنا',
    'admin.product_available': 'متوفر للطلب',
    'admin.search_placeholder': 'ابحث عن منتج...',
    'admin.all_categories': 'كل الأقسام',
    'admin.no_products': 'لا توجد منتجات تطابق بحثك',
    'admin.no_products_subtitle': 'جرب البحث بكلمات أخرى أو اختر قسم آخر',
    'admin.settings_general': 'الإعدادات العامة',
    'admin.settings_logo': 'لوجو المطعم',
    'admin.settings_logo_subtitle': 'يظهر في المنيو والفواتير',
    'admin.settings_logo_change': 'تغيير اللوجو',
    'admin.settings_name': 'اسم المطعم',
    'admin.settings_whatsapp': 'رقم الواتساب (بدون +)',
    'admin.settings_wallet': 'رقم المحفظة (فودافون كاش / غيره)',
    'admin.settings_delivery': 'رسوم التوصيل (ج.م)',
    'admin.settings_address': 'عنوان المطعم',
    'admin.settings_hours': 'مواعيد العمل',
    'admin.settings_hours_from': 'من',
    'admin.settings_hours_to': 'إلى',
    'admin.settings_is_open': 'المطعم مفتوح الآن',
    'admin.settings_payment': 'طرق الدفع المتاحة',
    'admin.settings_instapay_handle': 'رقم أو عنوان InstaPay',
    'admin.settings_card_details': 'تعليمات الدفع بالفيزا',
    'admin.settings_social': 'روابط التواصل الاجتماعي',
    'admin.settings_qr_title': 'QR Code المنيو',
    'admin.settings_qr_subtitle': 'اطبع هذا الكود وضعه على طاولات المطعم ليتمكن الزبائن من فتح المنيو مباشرة',
    'admin.settings_qr_download': 'تحميل الصورة',
    'admin.settings_qr_open': 'فتح المنيو',
    'admin.nav_overview': 'نظرة عامة',
    'admin.nav_orders': 'الطلبات',
    'admin.nav_products': 'المنتجات',
    'admin.nav_categories': 'الأقسام',
    'admin.nav_offers': 'العروض',
    'admin.nav_errors': 'سجل الأخطاء',
    'admin.nav_settings': 'الإعدادات',
    'admin.nav_database': 'قاعدة البيانات',
    'admin.nav_back_to_menu': 'العودة للمنيو',
    'admin.error_alert': 'خطأ في المنيو!',
    'common.currency': 'ج.م',
    'common.items': 'منتجات',
    'common.developed_by': 'تم التطوير بواسطة',
    'product.removed': 'تم حذف المنتج من السلة',
    'product.added': 'تم إضافة {name} للسلة',
    'search.no_results': 'لا توجد نتائج',
    'search.no_results_subtitle': 'جرب البحث بكلمات أخرى أو اختر قسماً آخر',
    'cart.validation_error': 'يرجى إكمال البيانات المطلوبة بشكل صحيح',
    'cart.error_sending': 'حدث خطأ أثناء إرسال الطلب، يرجى المحاولة مرة أخرى',
    'cart.name_required': 'الاسم مطلوب',
    'cart.phone_required': 'رقم الموبايل مطلوب',
    'cart.phone_invalid': 'رقم الموبايل غير صحيح',
    'cart.address_required': 'العنوان مطلوب للتوصيل',
    'cart.screenshot_required': 'يجب إرفاق صورة التحويل',
    'cart.clear_confirm': 'هل أنت متأكد من رغبتك في حذف جميع المنتجات من السلة؟',
    'cart.cleared_success': 'تم مسح السلة بنجاح',
    'cart.instapay_handle': 'عنوان InstaPay:',
    'cart.wallet_number': 'رقم التحويل:',
    'cart.attach_screenshot': 'أرفق صورة التحويل (سكرين شوت)',
    'cart.order_invoice': 'فاتورة طلب طعام - Order Invoice',
    'cart.customer_details': 'تفاصيل العميل',
    'cart.order_id': 'رقم الطلب',
    'cart.date': 'التاريخ',
    'cart.thank_you': 'شكراً لاختياركم لنا',
    'cart.pickup_location': 'استلام من المكان',
    'admin.overview_title': 'نظرة عامة',
    'admin.view_menu': 'عرض المنيو',
    'admin.last_update': 'آخر تحديث',
    'admin.db_local_title': 'أنت تعمل في وضع "التخزين المحلي"',
    'admin.db_local_subtitle': 'قاعدة بيانات MySQL غير متصلة. يتم حفظ البيانات حالياً في ملف محلي. يرجى إعداد MySQL لضمان استقرار البيانات في الإنتاج.',
    'admin.db_setup': 'إعداد MySQL',
    'admin.db_error_title': 'قاعدة البيانات غير متصلة',
    'admin.db_error_fetch': 'خطأ في جلب البيانات',
    'admin.db_error_subtitle': 'يرجى إعداد بيانات الاتصال بـ MySQL لتفعيل لوحة التحكم.',
    'admin.db_settings': 'إعدادات قاعدة البيانات',
    'admin.stat_total_orders': 'إجمالي الطلبات',
    'admin.stat_total_revenue': 'إجمالي المبيعات',
    'admin.stat_pending_orders': 'طلبات قيد الانتظار',
    'admin.stat_completed_orders': 'طلبات مكتملة',
    'admin.stat_cancelled_orders': 'طلبات ملغاة',
    'admin.quick_add_product': 'إضافة منتج',
    'admin.quick_add_product_subtitle': 'إضافة وجبة جديدة للمنيو',
    'admin.quick_manage_orders': 'إدارة الطلبات',
    'admin.quick_manage_orders_subtitle': 'متابعة الطلبات الجديدة',
    'admin.quick_settings': 'إعدادات النظام',
    'admin.quick_settings_subtitle': 'تعديل أرقام التواصل والرسوم',
    'admin.chart_sales': 'إحصائيات المبيعات',
    'admin.chart_last_7_days': 'آخر 7 أيام',
    'admin.chart_top_selling': 'الأكثر مبيعاً',
    'admin.chart_top_5': 'أفضل 5 منتجات',
    'admin.chart_categories': 'توزيع الأصناف',
    'admin.chart_categories_subtitle': 'عدد المنتجات لكل صنف',
    'admin.chart_revenue_by_category': 'المبيعات حسب الصنف',
    'admin.chart_revenue_by_category_subtitle': 'إجمالي المبيعات لكل صنف',
    'admin.chart_status_distribution': 'توزيع الحالات',
    'admin.recent_orders': 'آخر الطلبات',
    'admin.recent_orders_subtitle': 'أحدث 5 طلبات تم استلامها',
    'admin.view_all': 'عرض الكل',
    'admin.order_customer': 'العميل',
    'admin.order_type': 'النوع',
    'admin.order_total': 'الإجمالي',
    'admin.order_status': 'الحالة',
    'admin.order_date': 'التاريخ',
    'admin.no_orders': 'لا توجد طلبات حالياً',
    'admin.status_pending': 'قيد الانتظار',
    'admin.status_completed': 'مكتمل',
    'admin.status_cancelled': 'ملغي',
    'admin.type_delivery': 'توصيل',
    'admin.type_pickup': 'استلام',
    'admin.orders_title': 'إدارة الطلبات',
    'admin.orders_search_placeholder': 'بحث بالاسم أو الرقم...',
    'admin.orders_filter_all': 'الكل',
    'admin.orders_filter_pending': 'قيد الانتظار',
    'admin.orders_filter_completed': 'مكتملة',
    'admin.orders_filter_cancelled': 'ملغاة',
    'admin.orders_no_orders': 'لا توجد طلبات حالياً',
    'admin.orders_customer': 'العميل',
    'admin.orders_phone': 'الهاتف',
    'admin.orders_address': 'العنوان',
    'admin.orders_type': 'النوع',
    'admin.orders_payment': 'طريقة الدفع',
    'admin.orders_total': 'الإجمالي',
    'admin.orders_status': 'الحالة',
    'admin.orders_actions': 'الإجراءات',
    'admin.orders_view_details': 'عرض التفاصيل',
    'admin.orders_print_invoice': 'طباعة الفاتورة',
    'admin.orders_copy_details': 'نسخ التفاصيل',
    'admin.orders_delete': 'حذف الطلب',
    'admin.orders_mark_completed': 'تم التوصيل',
    'admin.orders_mark_cancelled': 'إلغاء',
    'admin.orders_details_title': 'تفاصيل الطلب',
    'admin.orders_delivery_info': 'معلومات التوصيل',
    'admin.orders_items_ordered': 'الأصناف المطلوبة',
    'admin.orders_payment_screenshot': 'صورة التحويل',
    'admin.orders_open_image': 'فتح الصورة',
    'admin.orders_call_customer': 'اتصال بالعميل',
    'admin.orders_delivery_home': 'توصيل للمنزل',
    'admin.orders_pickup_restaurant': 'استلام من المطعم',
    'admin.orders_confirm_delete': 'هل أنت متأكد من حذف هذا الطلب؟',
    'admin.orders_updated_success': 'تم تحديث حالة الطلب',
    'admin.orders_deleted_success': 'تم حذف الطلب بنجاح',
    'admin.orders_delete_failed': 'فشل في حذف الطلب',
    'admin.orders_update_failed': 'فشل في تحديث حالة الطلب',
    'admin.orders_details_copied': 'تم نسخ تفاصيل الطلب',
    'admin.orders_new_alert': 'يوجد طلب جديد!',
    'admin.orders_new_desc': 'تم استلام طلب جديد في القائمة.',
    'admin.orders_invoice_title': 'فاتورة طلب',
    'admin.orders_date': 'التاريخ',
    'admin.orders_final_total': 'الإجمالي النهائي',
    'admin.orders_item': 'الصنف',
    'admin.orders_quantity': 'الكمية',
    'admin.orders_price': 'السعر',
    'admin.product_image_large': 'حجم الصورة كبير جداً (الحد الأقصى 2 ميجابايت)',
    'admin.product_updated': 'تم تحديث المنتج بنجاح',
    'admin.product_added': 'تم إضافة المنتج بنجاح',
    'admin.product_delete_confirm': 'هل أنت متأكد من حذف هذا المنتج؟',
    'admin.product_deleted': 'تم حذف المنتج بنجاح',
    'admin.product_marked_unavailable': 'تم جعل المنتج غير متوفر',
    'admin.product_marked_available': 'تم جعل المنتج متوفر',
    'admin.product_select_category': 'اختر القسم',
    'admin.categories_title': 'إدارة الأقسام',
    'admin.categories_search': 'بحث عن قسم...',
    'admin.categories_add': 'إضافة قسم',
    'admin.categories_order': 'الترتيب',
    'admin.categories_no_results': 'لا توجد نتائج لبحثك',
    'admin.categories_no_data': 'لا توجد أقسام بعد',
    'admin.categories_edit_title': 'تعديل قسم',
    'admin.categories_add_title': 'إضافة قسم جديد',
    'admin.categories_name_label': 'اسم القسم',
    'admin.categories_order_label': 'الترتيب (للعرض)',
    'admin.categories_save': 'حفظ التعديلات',
    'admin.categories_updated': 'تم تحديث القسم بنجاح',
    'admin.categories_added': 'تم إضافة القسم بنجاح',
    'admin.categories_delete_confirm': 'هل أنت متأكد من حذف هذا القسم؟ سيتم حذف جميع المنتجات التابعة له (اختياري)',
    'admin.categories_deleted': 'تم حذف القسم بنجاح',
    'admin.offers_title': 'إدارة العروض والخصومات',
    'admin.offers_add': 'إضافة عرض جديد',
    'admin.offers_no_data': 'لا توجد عروض حالياً',
    'admin.offers_inactive': 'غير نشط',
    'admin.offers_active': 'نشط',
    'admin.offers_activate': 'تفعيل',
    'admin.offers_edit_title': 'تعديل عرض',
    'admin.offers_add_title': 'إضافة عرض جديد',
    'admin.offers_label_title': 'عنوان العرض',
    'admin.offers_placeholder_title': 'مثال: خصم 50% على البيتزا',
    'admin.offers_label_desc': 'وصف العرض',
    'admin.offers_placeholder_desc': 'تفاصيل العرض وشروطه...',
    'admin.offers_label_image': 'صورة العرض',
    'admin.offers_upload_local': 'رفع صورة من الجهاز',
    'admin.offers_placeholder_url': 'أو ضع رابط الصورة هنا',
    'admin.offers_label_active': 'عرض نشط ويظهر للزبائن',
    'admin.offers_save': 'حفظ التعديلات',
    'admin.offers_updated': 'تم تحديث العرض بنجاح',
    'admin.offers_added': 'تم إضافة العرض بنجاح',
    'admin.offers_delete_confirm': 'هل أنت متأكد من حذف هذا العرض؟',
    'admin.offers_deleted': 'تم حذف العرض بنجاح',
    'admin.offers_disabled': 'تم تعطيل العرض',
    'admin.offers_enabled': 'تم تفعيل العرض',
    'admin.settings_saved': 'تم حفظ الإعدادات بنجاح',
    'admin.settings_saved_btn': 'تم الحفظ!',
    'admin.settings_logo_large': 'حجم اللوجو كبير جداً (الحد الأقصى 1 ميجابايت)',
    'admin.settings_card_placeholder': 'مثال: سيتم إرسال رابط دفع بعد تأكيد الطلب...',
    'admin.settings_facebook_placeholder': 'رابط فيسبوك',
    'admin.settings_instagram_placeholder': 'رابط انستجرام',
    'admin.settings_tiktok_placeholder': 'رابط تيك توك',
    'admin.nav_cashier': 'الكاشير',
    'admin.nav_staff': 'الموظفين',
    'admin.cashier_title': 'نظام الكاشير',
    'admin.cashier_customer_info': 'بيانات العميل',
    'admin.cashier_order_summary': 'ملخص الطلب',
    'admin.cashier_confirm_order': 'تأكيد الطلب',
    'admin.cashier_print_receipt': 'طباعة الإيصال',
    'admin.staff_title': 'إدارة الموظفين',
    'admin.staff_add': 'إضافة موظف',
    'admin.staff_username': 'اسم المستخدم',
    'admin.staff_role': 'الدور',
    'admin.staff_status': 'الحالة',
    'admin.staff_active': 'نشط',
    'admin.staff_inactive': 'معطل',
    'admin.role_admin': 'مدير',
    'admin.role_staff': 'موظف',
    'admin.role_cashier': 'كاشير',
  },
  en: {
    'nav.menu': 'Menu',
    'nav.cart': 'Cart',
    'nav.admin': 'Admin',
    'hero.title': "Bite's Menu",
    'hero.subtitle': 'Order the most delicious meals with one click',
    'search.placeholder': 'Search for your favorite meal...',
    'categories.all': 'All',
    'offers.title': 'Exclusive Offers',
    'offers.limited': 'Limited Time Offer',
    'product.available': 'Available',
    'product.unavailable': 'Unavailable',
    'product.add_to_cart': 'Add to Cart',
    'product.details': 'View Details',
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.empty_subtitle': 'Start adding some delicious meals to your menu',
    'cart.browse': 'Browse Menu',
    'cart.clear': 'Clear Cart',
    'cart.order_details': 'Order Details',
    'cart.delivery': 'Delivery',
    'cart.pickup': 'Pickup',
    'cart.name_placeholder': 'Full Name',
    'cart.phone_placeholder': 'Phone Number',
    'cart.address_placeholder': 'Detailed Address',
    'cart.notes_placeholder': 'Additional Notes',
    'cart.payment_method': 'Payment Method',
    'cart.cash': 'Cash on Delivery',
    'cart.instapay': 'InstaPay',
    'cart.card': 'Visa / Mastercard',
    'cart.wallet': 'Mobile Wallet',
    'cart.subtotal': 'Subtotal',
    'cart.delivery_fee': 'Delivery Fee',
    'cart.total': 'Total',
    'cart.send_whatsapp': 'Send Order via WhatsApp',
    'cart.download_pdf': 'Download Invoice (PDF)',
    'cart.success_title': 'Order Sent Successfully!',
    'cart.success_subtitle': "Thank you for choosing Bite's. We will contact you soon via WhatsApp to confirm your order.",
    'cart.back_to_menu': 'Back to Menu',
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'admin.title': 'Admin Dashboard',
    'admin.products': 'Products',
    'admin.categories': 'Categories',
    'admin.orders': 'Orders',
    'admin.offers': 'Offers',
    'admin.settings': 'Settings',
    'admin.errors': 'Error Logs',
    'admin.logout': 'Logout',
    'login.title': 'Admin Login',
    'login.subtitle': 'Enter password to access dashboard',
    'login.password_placeholder': 'Password',
    'login.button': 'Login',
    'login.error': 'Incorrect password',
    'login.welcome': 'Welcome',
    'login.admin_role': 'System Admin',
    'admin.add_product': 'Add Product',
    'admin.edit_product': 'Edit Product',
    'admin.product_name': 'Product Name',
    'admin.product_price': 'Price',
    'admin.product_category': 'Category',
    'admin.product_description': 'Description',
    'admin.product_image': 'Product Image',
    'admin.product_upload': 'Upload from Device',
    'admin.product_url': 'Or paste image URL',
    'admin.product_available': 'Available for Order',
    'admin.search_placeholder': 'Search for a product...',
    'admin.all_categories': 'All Categories',
    'admin.no_products': 'No products match your search',
    'admin.no_products_subtitle': 'Try searching with other words or choose another category',
    'admin.settings_general': 'General Settings',
    'admin.settings_logo': 'Restaurant Logo',
    'admin.settings_logo_subtitle': 'Appears in menu and invoices',
    'admin.settings_logo_change': 'Change Logo',
    'admin.settings_name': 'Restaurant Name',
    'admin.settings_whatsapp': 'WhatsApp Number (without +)',
    'admin.settings_wallet': 'Wallet Number (Vodafone Cash / etc.)',
    'admin.settings_delivery': 'Delivery Fee (EGP)',
    'admin.settings_address': 'Restaurant Address',
    'admin.settings_hours': 'Opening Hours',
    'admin.settings_hours_from': 'From',
    'admin.settings_hours_to': 'To',
    'admin.settings_is_open': 'Restaurant is Open Now',
    'admin.settings_payment': 'Available Payment Methods',
    'admin.settings_instapay_handle': 'InstaPay Number or Handle',
    'admin.settings_card_details': 'Visa Payment Instructions',
    'admin.settings_social': 'Social Media Links',
    'admin.settings_qr_title': 'Menu QR Code',
    'admin.settings_qr_subtitle': 'Print this code and place it on restaurant tables so customers can open the menu directly',
    'admin.settings_qr_download': 'Download Image',
    'admin.settings_qr_open': 'Open Menu',
    'admin.nav_overview': 'Overview',
    'admin.nav_orders': 'Orders',
    'admin.nav_products': 'Products',
    'admin.nav_categories': 'Categories',
    'admin.nav_offers': 'Offers',
    'admin.nav_errors': 'Error Logs',
    'admin.nav_settings': 'Settings',
    'admin.nav_database': 'Database',
    'admin.nav_back_to_menu': 'Back to Menu',
    'admin.error_alert': 'Menu Error!',
    'common.currency': 'EGP',
    'common.items': 'items',
    'common.developed_by': 'Developed by',
    'product.removed': 'Product removed from cart',
    'product.added': 'Added {name} to cart',
    'search.no_results': 'No results found',
    'search.no_results_subtitle': 'Try searching with different keywords or choose another category',
    'cart.validation_error': 'Please complete the required information correctly',
    'cart.error_sending': 'Error sending order, please try again',
    'cart.name_required': 'Name is required',
    'cart.phone_required': 'Phone number is required',
    'cart.phone_invalid': 'Invalid phone number',
    'cart.address_required': 'Address is required for delivery',
    'cart.screenshot_required': 'Transfer screenshot is required',
    'cart.clear_confirm': 'Are you sure you want to remove all items from the cart?',
    'cart.cleared_success': 'Cart cleared successfully',
    'cart.instapay_handle': 'InstaPay Handle:',
    'cart.wallet_number': 'Wallet Number:',
    'cart.attach_screenshot': 'Attach transfer screenshot',
    'cart.order_invoice': 'Order Invoice',
    'cart.customer_details': 'Customer Details',
    'cart.order_id': 'Order ID',
    'cart.date': 'Date',
    'cart.thank_you': 'Thank you for choosing us!',
    'cart.pickup_location': 'Pickup from location',
    'admin.overview_title': 'Overview',
    'admin.view_menu': 'View Menu',
    'admin.last_update': 'Last update',
    'admin.db_local_title': 'You are working in "Local Storage" mode',
    'admin.db_local_subtitle': 'MySQL database is not connected. Data is currently saved in a local file. Please set up MySQL to ensure data stability in production.',
    'admin.db_setup': 'Set up MySQL',
    'admin.db_error_title': 'Database not connected',
    'admin.db_error_fetch': 'Error fetching data',
    'admin.db_error_subtitle': 'Please set up MySQL connection details to activate the dashboard.',
    'admin.db_settings': 'Database Settings',
    'admin.stat_total_orders': 'Total Orders',
    'admin.stat_total_revenue': 'Total Revenue',
    'admin.stat_pending_orders': 'Pending Orders',
    'admin.stat_completed_orders': 'Completed Orders',
    'admin.stat_cancelled_orders': 'Cancelled Orders',
    'admin.quick_add_product': 'Add Product',
    'admin.quick_add_product_subtitle': 'Add a new meal to the menu',
    'admin.quick_manage_orders': 'Manage Orders',
    'admin.quick_manage_orders_subtitle': 'Follow up on new orders',
    'admin.quick_settings': 'System Settings',
    'admin.quick_settings_subtitle': 'Edit contact numbers and fees',
    'admin.chart_sales': 'Sales Statistics',
    'admin.chart_last_7_days': 'Last 7 days',
    'admin.chart_top_selling': 'Top Selling',
    'admin.chart_top_5': 'Top 5 products',
    'admin.chart_categories': 'Category Distribution',
    'admin.chart_categories_subtitle': 'Number of products per category',
    'admin.chart_revenue_by_category': 'Revenue by Category',
    'admin.chart_revenue_by_category_subtitle': 'Total revenue per category',
    'admin.chart_status_distribution': 'Status Distribution',
    'admin.recent_orders': 'Recent Orders',
    'admin.recent_orders_subtitle': 'Latest 5 orders received',
    'admin.view_all': 'View All',
    'admin.order_customer': 'Customer',
    'admin.order_type': 'Type',
    'admin.order_total': 'Total',
    'admin.order_status': 'Status',
    'admin.order_date': 'Date',
    'admin.no_orders': 'No orders currently',
    'admin.status_pending': 'Pending',
    'admin.status_completed': 'Completed',
    'admin.status_cancelled': 'Cancelled',
    'admin.type_delivery': 'Delivery',
    'admin.type_pickup': 'Pickup',
    'admin.orders_title': 'Orders Management',
    'admin.orders_search_placeholder': 'Search by name or number...',
    'admin.orders_filter_all': 'All',
    'admin.orders_filter_pending': 'Pending',
    'admin.orders_filter_completed': 'Completed',
    'admin.orders_filter_cancelled': 'Cancelled',
    'admin.orders_no_orders': 'No orders found',
    'admin.orders_customer': 'Customer',
    'admin.orders_phone': 'Phone',
    'admin.orders_address': 'Address',
    'admin.orders_type': 'Type',
    'admin.orders_payment': 'Payment Method',
    'admin.orders_total': 'Total',
    'admin.orders_status': 'Status',
    'admin.orders_actions': 'Actions',
    'admin.orders_view_details': 'View Details',
    'admin.orders_print_invoice': 'Print Invoice',
    'admin.orders_copy_details': 'Copy Details',
    'admin.orders_delete': 'Delete Order',
    'admin.orders_mark_completed': 'Mark Completed',
    'admin.orders_mark_cancelled': 'Cancel',
    'admin.orders_details_title': 'Order Details',
    'admin.orders_delivery_info': 'Delivery Info',
    'admin.orders_items_ordered': 'Items Ordered',
    'admin.orders_payment_screenshot': 'Payment Screenshot',
    'admin.orders_open_image': 'Open Image',
    'admin.orders_call_customer': 'Call Customer',
    'admin.orders_delivery_home': 'Home Delivery',
    'admin.orders_pickup_restaurant': 'Restaurant Pickup',
    'admin.orders_confirm_delete': 'Are you sure you want to delete this order?',
    'admin.orders_updated_success': 'Order status updated',
    'admin.orders_deleted_success': 'Order deleted successfully',
    'admin.orders_delete_failed': 'Failed to delete order',
    'admin.orders_update_failed': 'Failed to update order status',
    'admin.orders_details_copied': 'Order details copied',
    'admin.orders_new_alert': 'New Order!',
    'admin.orders_new_desc': 'A new order has been received.',
    'admin.orders_invoice_title': 'Order Invoice',
    'admin.orders_date': 'Date',
    'admin.orders_final_total': 'Final Total',
    'admin.orders_item': 'Item',
    'admin.orders_quantity': 'Quantity',
    'admin.orders_price': 'Price',
    'admin.product_image_large': 'Image size is too large (max 2MB)',
    'admin.product_updated': 'Product updated successfully',
    'admin.product_added': 'Product added successfully',
    'admin.product_delete_confirm': 'Are you sure you want to delete this product?',
    'admin.product_deleted': 'Product deleted successfully',
    'admin.product_marked_unavailable': 'Product marked as unavailable',
    'admin.product_marked_available': 'Product marked as available',
    'admin.product_select_category': 'Select Category',
    'admin.categories_title': 'Manage Categories',
    'admin.categories_search': 'Search for a category...',
    'admin.categories_add': 'Add Category',
    'admin.categories_order': 'Order',
    'admin.categories_no_results': 'No results found',
    'admin.categories_no_data': 'No categories yet',
    'admin.categories_edit_title': 'Edit Category',
    'admin.categories_add_title': 'Add New Category',
    'admin.categories_name_label': 'Category Name',
    'admin.categories_order_label': 'Order (for display)',
    'admin.categories_save': 'Save Changes',
    'admin.categories_updated': 'Category updated successfully',
    'admin.categories_added': 'Category added successfully',
    'admin.categories_delete_confirm': 'Are you sure you want to delete this category? All related products will be deleted (optional)',
    'admin.categories_deleted': 'Category deleted successfully',
    'admin.offers_title': 'Manage Offers & Discounts',
    'admin.offers_add': 'Add New Offer',
    'admin.offers_no_data': 'No offers currently',
    'admin.offers_inactive': 'Inactive',
    'admin.offers_active': 'Active',
    'admin.offers_activate': 'Activate',
    'admin.offers_edit_title': 'Edit Offer',
    'admin.offers_add_title': 'Add New Offer',
    'admin.offers_label_title': 'Offer Title',
    'admin.offers_placeholder_title': 'Example: 50% off pizza',
    'admin.offers_label_desc': 'Offer Description',
    'admin.offers_placeholder_desc': 'Offer details and terms...',
    'admin.offers_label_image': 'Offer Image',
    'admin.offers_upload_local': 'Upload image from device',
    'admin.offers_placeholder_url': 'Or paste image link here',
    'admin.offers_label_active': 'Active offer visible to customers',
    'admin.offers_save': 'Save Changes',
    'admin.offers_updated': 'Offer updated successfully',
    'admin.offers_added': 'Offer added successfully',
    'admin.offers_delete_confirm': 'Are you sure you want to delete this offer?',
    'admin.offers_deleted': 'Offer deleted successfully',
    'admin.offers_disabled': 'Offer disabled',
    'admin.offers_enabled': 'Offer enabled',
    'admin.settings_saved': 'Settings saved successfully',
    'admin.settings_saved_btn': 'Saved!',
    'admin.settings_logo_large': 'Logo size is too large (max 1MB)',
    'admin.settings_card_placeholder': 'Example: A payment link will be sent after order confirmation...',
    'admin.settings_facebook_placeholder': 'Facebook link',
    'admin.settings_instagram_placeholder': 'Instagram link',
    'admin.settings_tiktok_placeholder': 'TikTok link',
    'admin.nav_cashier': 'Cashier',
    'admin.nav_staff': 'Staff',
    'admin.cashier_title': 'Cashier System',
    'admin.cashier_customer_info': 'Customer Info',
    'admin.cashier_order_summary': 'Order Summary',
    'admin.cashier_confirm_order': 'Confirm Order',
    'admin.cashier_print_receipt': 'Print Receipt',
    'admin.staff_title': 'Staff Management',
    'admin.staff_add': 'Add Staff',
    'admin.staff_username': 'Username',
    'admin.staff_role': 'Role',
    'admin.staff_status': 'Status',
    'admin.staff_active': 'Active',
    'admin.staff_inactive': 'Inactive',
    'admin.role_admin': 'Admin',
    'admin.role_staff': 'Staff',
    'admin.role_cashier': 'Cashier',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app_lang');
    return (saved as Language) || 'ar';
  });

  useEffect(() => {
    localStorage.setItem('app_lang', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
